name: flutter_gemini
description: Flutter Google Gemini SDK. Google Gemini is a set of cutting-edge large language models 
  (LLMs) designed to be the driving force behind Google's future AI initiatives.
version: 2.0.0-dev-1
homepage: https://github.com/babakcode/flutter_gemini
topics:
  - gemini
  - ai
  - google-gemini
  - flutter-gemini
screenshots:
  - description: Flutter_Gemini example screenshot
    path: example/screenshots/gemini_screenshot.png
  - description: Flutter_Gemini example
    path: example/screenshots/gemini_cover.jpeg

platforms:
  android:
  ios:
  web:
  linux:
  windows:
  macos:

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio:
  flutter:
    sdk: flutter
  freezed_annotation:
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_convert: ^1.1.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.5

flutter:
